---

- name: Include os specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}_{{ ansible_distribution_version }}_{{ ansible_architecture }}.yml'
    - '{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml'
    - '{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_os_family }}.yml'
  tags:
    - 'role::subscribe_rhn'
    - 'role::subscribe_rhn:install'
    - 'role::subscribe_rhn:config'

# - include_tasks: installation.yml
#  tags:
#    - 'role::subscribe_rhn'
#    - 'role::subscribe_rhn:install'

- name: Run configuration tasks
  include_tasks: configuration.yml
  tags:
    - 'role::subscribe_rhn'
    - 'role::subscribe_rhn:config'
